version: '3'
services:
        redis-server:
                image: redis:6.0.6-alpine
        flask-server:
                build: .
                volumes:
                        - .:/app
                ports:
                        - "8000:5000"
                depends_on:
                        - redis-server
                stdin_open: true
